language: java
sudo: false
jobs:
  include:
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: jdk9
    - os: linux
      jdk: jdk10
    - os: linux
      jdk: openjdk11
    - os: osx
      jdk: jdk8
    - os: osx
      jdk: jdk9
    - os: osx
      jdk: jdk10
    - os: osx
      jdk: openjdk11

script: mvn clean install
