
package com.amazonaws.mws.feeds.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Marketplace" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Merchant" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="NextToken" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MWSAuthToken" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Wed Feb 18 13:28:59 PST 2009
 *
 * @author dmytro
 * @version $Id: $Id
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "marketplace",
    "merchant",
    "nextToken",
    "mwsAuthToken"
})
@XmlRootElement(name = "GetReportRequestListByNextTokenRequest")
public class GetReportRequestListByNextTokenRequest {

    @XmlElement(name = "Marketplace")
    protected String marketplace;
    @XmlElement(name = "Merchant", required = true)
    protected String merchant;
    @XmlElement(name = "NextToken", required = true)
    protected String nextToken;
    @XmlElement(name = "MWSAuthToken")
    protected String mwsAuthToken;

    /**
     * Default constructor
     */
    public GetReportRequestListByNextTokenRequest() {
        super();
    }

    /**
     * Value constructor
     *
     * @param marketplace a {@link java.lang.String} object.
     * @param merchant a {@link java.lang.String} object.
     * @param nextToken a {@link java.lang.String} object.
     */
    public GetReportRequestListByNextTokenRequest(final String marketplace, final String merchant, final String nextToken) {
        this(marketplace, merchant, nextToken, null);
    }
    
    /**
     * <p>Constructor for GetReportRequestListByNextTokenRequest.</p>
     *
     * @param marketplace a {@link java.lang.String} object.
     * @param merchant a {@link java.lang.String} object.
     * @param nextToken a {@link java.lang.String} object.
     * @param mwsAuthToken a {@link java.lang.String} object.
     */
    public GetReportRequestListByNextTokenRequest(final String marketplace, 
            final String merchant, 
            final String nextToken,
            final String mwsAuthToken) {
        this.marketplace = marketplace;
        this.merchant = merchant;
        this.nextToken = nextToken;
        this.mwsAuthToken = mwsAuthToken;
    }

    /**
     * Gets the value of the marketplace property.
     *
     * @deprecated  See {@link #setMarketplace(String)}
     * @return a {@link java.lang.String} object.
     */
    public String getMarketplace() {
        return marketplace;
    }

    /**
     * Sets the value of the marketplace property.
     *
     * @deprecated Not used anymore.  MWS ignores this parameter, but it is left
     * in here for backwards compatibility.
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setMarketplace(String value) {
        this.marketplace = value;
    }

    /**
     * <p>isSetMarketplace.</p>
     *
     * @deprecated  See {@link #setMarketplace(String)}
     * @return a boolean.
     */
    public boolean isSetMarketplace() {
        return (this.marketplace!= null);
    }

    /**
     * Gets the value of the merchant property.
     *
     * @return a {@link java.lang.String} object.
     */
    public String getMerchant() {
        return merchant;
    }

    /**
     * Sets the value of the merchant property.
     *
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setMerchant(String value) {
        this.merchant = value;
    }

    /**
     * <p>isSetMerchant.</p>
     *
     * @return a boolean.
     */
    public boolean isSetMerchant() {
        return (this.merchant!= null);
    }

    /**
     * Gets the value of the nextToken property.
     *
     * @return a {@link java.lang.String} object.
     */
    public String getNextToken() {
        return nextToken;
    }

    /**
     * Sets the value of the nextToken property.
     *
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setNextToken(String value) {
        this.nextToken = value;
    }

    /**
     * <p>isSetNextToken.</p>
     *
     * @return a boolean.
     */
    public boolean isSetNextToken() {
        return (this.nextToken!= null);
    }
    
    /**
     * Gets the value of the mwsAuthToken property.
     *
     * possible object is
     *     {@link java.lang.String}
     *
     * @return a {@link java.lang.String} object.
     */
    public String getMWSAuthToken() {
    	return mwsAuthToken;
    }
    
    /**
     * Sets the value of the mwsAuthToken property
     *
     * @param authTokenValue
     * 		allowed object is
     * 		{@link java.lang.String}
     */
    public void setMWSAuthToken(String authTokenValue) {
    	this.mwsAuthToken = authTokenValue;
    }

    /**
     * <p>isSetMWSAuthToken.</p>
     *
     * @return a boolean.
     */
    public boolean isSetMWSAuthToken() {
    	return (this.mwsAuthToken!=null);
    }

    /**
     * Sets the value of the Marketplace property.
     *
     * @deprecated  See {@link #setMarketplace(String)}
     * @param value a {@link java.lang.String} object.
     * @return a {@link com.amazonaws.mws.feeds.model.GetReportRequestListByNextTokenRequest} object.
     */
    public GetReportRequestListByNextTokenRequest withMarketplace(String value) {
        setMarketplace(value);
        return this;
    }

    /**
     * Sets the value of the Merchant property.
     *
     * @param value a {@link java.lang.String} object.
     * @return a {@link com.amazonaws.mws.feeds.model.GetReportRequestListByNextTokenRequest} object.
     */
    public GetReportRequestListByNextTokenRequest withMerchant(String value) {
        setMerchant(value);
        return this;
    }
    
    /**
     * Sets the value of the MWSAuthToken property.
     *
     * @param value a {@link java.lang.String} object.
     * @return a {@link com.amazonaws.mws.feeds.model.GetReportRequestListByNextTokenRequest} object.
     */
    public GetReportRequestListByNextTokenRequest withMWSAuthToken(String value) {
        setMWSAuthToken(value);
        return this;
    }

    /**
     * Sets the value of the NextToken property.
     *
     * @param value a {@link java.lang.String} object.
     * @return a {@link com.amazonaws.mws.feeds.model.GetReportRequestListByNextTokenRequest} object.
     */
    public GetReportRequestListByNextTokenRequest withNextToken(String value) {
        setNextToken(value);
        return this;
    }
    


    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetMarketplace()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("Marketplace"));
            json.append(" : ");
            json.append(quoteJSON(getMarketplace()));
            first = false;
        }
        if (isSetMerchant()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("Merchant"));
            json.append(" : ");
            json.append(quoteJSON(getMerchant()));
            first = false;
        }
        if (isSetNextToken()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("NextToken"));
            json.append(" : ");
            json.append(quoteJSON(getNextToken()));
            first = false;
        }
        if (isSetMWSAuthToken()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("MWSAuthToken"));
            json.append(" : ");
            json.append(quoteJSON(getMWSAuthToken()));
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
