name: os-and-java-versions-compatability
concurrency: 'os-and-java-versions-compatability'

on:
  push:
  workflow_dispatch: # Allow for running this manually.

jobs:
  update-stats:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, macos-11, macos-10.15, windows-2022, windows-2019, windows-2016]
        java: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
      fail-fast: false
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Compile source-code
        run: mvn clean install
